# scikit learn for training and evaluating ML Models

**Project Life Cycle**

*1. Import the dataset*

*2. Prepare the Train, Test sets for training and testing model*

*3. Choose the ML model*

*4. Fitting the MOdel to Data*

*5. Let the model make Predictions*

*6. Evaluate the predictions(check accuracy and others)*

*7. HyperParameters Tuning for best results*

In [2]:
import pandas as pd
# importing the dataset
patients_record = pd.read_csv('../heart.csv')
patients_record

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0