In [1]:
import pandas as pd

In [2]:
phones = pd.read_csv("phones.csv")

In [3]:
phones

         Phone Name Manufacturer Storage Memory  Price (USD) Internet Network
0  Galaxy S22 Ultra      Samsung   512GB   12GB         1099               5G
1     iPhone 14 Pro        Apple   256GB    6GB          999               5G
2           Pixel 7       Google   128GB    8GB          599               5G
3       OnePlus 10T      OnePlus   256GB   16GB          649               5G
4     Redmi Note 11       Xiaomi   128GB    4GB          249           4G LTE
5      Moto G Power     Motorola    64GB    4GB          199           4G LTE
6        Nokia G400        Nokia   128GB    6GB          299               5G
7           P50 Pro       Huawei   256GB    8GB          899           4G LTE
8      Oppo Find X5         Oppo   256GB   12GB          799               5G
9          Vivo X80         Vivo   512GB   12GB          749               5G

**some dataset comes with predefined patterns and that sometimes causes error in the program**

**how to handle such datasets, we use the sample(frac = x) method to handle this**
# lets shuffle these rows

In [4]:
phones.sample(frac=1)

         Phone Name Manufacturer Storage Memory  Price (USD) Internet Network
4     Redmi Note 11       Xiaomi   128GB    4GB          249           4G LTE
2           Pixel 7       Google   128GB    8GB          599               5G
6        Nokia G400        Nokia   128GB    6GB          299               5G
8      Oppo Find X5         Oppo   256GB   12GB          799               5G
0  Galaxy S22 Ultra      Samsung   512GB   12GB         1099               5G
1     iPhone 14 Pro        Apple   256GB    6GB          999               5G
3       OnePlus 10T      OnePlus   256GB   16GB          649               5G
9          Vivo X80         Vivo   512GB   12GB          749               5G
5      Moto G Power     Motorola    64GB    4GB          199           4G LTE
7           P50 Pro       Huawei   256GB    8GB          899           4G LTE